server:
  port: 8080
  undertow:
    accesslog:
      enabled: true
      dir: undertow-log
      prefix: access_log
      pattern:  '[%{time,yyyy-MM-dd HH:mm:ss.S z}] %b %l %u %I %v %a %m %U %s (%D ms)'
      rotate: true
      suffix: .log
    buffer-size: 1024
    worker-threads: 20
    direct-buffers: true

logging:
  config: classpath:log4j2-testing.yml
  path: ./.log

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&jdbcCompliantTruncation=false&allowMultiQueries=true&useAffectedRows=true
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      max-lifetime: 1800000
      connection-timeout: 30000
      read-only: false
      idle-timeout: 300000
      auto-commit: true
      connection-test-query: SELECT 1
      pool-name: HikariDataSource

  redis:
    host: localhost
    # 连接超时时间（记得添加单位，Duration）
    timeout: 10000
    # Redis默认情况下有16个分片，这里配置具体使用的分片
    # database: 0
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1ms
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0
  cache:
    # 一般来说是不用配置的，Spring Cache 会根据依赖的包自行装配
    type: redis